name: Laravel_build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copie .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Installation des dependences
      run: composer2 install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Génération de clé Artisan
      run: php artisan key:generate
    - name: Permission de répertoire
      run: chmod -R 777 storage bootstrap/cache
    - name: Création de la Base
      run: |
        mkdir -p database2
        touch database2/database.sqlite
    - name: Execution des tests (Unit & Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database2/database.sqlite
      run: vendor/bin/phpunit
